version: "3.7"
services:
    app:
        image: "devbase/app:${TAG:-latest}"
        build:
            args:
                user: ${APP_USER:-devusr}
                uid: ${APP_UID:-1000}
            context: ./
            dockerfile: Dockerfile
        container_name: dev-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - dev-network

    web:
        image: nginx:1.25.1
        container_name: dev-nginx
        restart: unless-stopped
        ports:
            - ${SERVER_PORT:-80}:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d/
        networks:
            - dev-network

    db:
        image: mysql:5.7
        container_name: dev-db
        restart: unless-stopped
        ports:
            - ${SERVER_PORT_DB:-3306}:3306
        volumes:
            - dbdata:/var/lib/mysql
        environment:
            - MYSQL_DATABASE=${DB_DATABASE:-homestead}
            - MYSQL_USER=${DB_USERNAME:-homestead}
            - MYSQL_PASSWORD=${DB_PASSWORD:-secret}
            - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-secret}
        networks:
            - dev-network

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - ${PHPMYADMIN_PORT_DB:-8080}:80
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${DB_HOST:-db}
            - PMA_USER=${DB_USERNAME:-homestead}
            - PMA_PASSWORD=${DB_PASSWORD:-secret}
        networks:
            - dev-network

    mailhog:
        image: mailhog/mailhog
        logging:
            driver: "none"
        ports:
            - ${MAIL_PORT:-1025}:1025
            - ${MAILHOG_PORT:-8025}:8025
        networks:
            - dev-network

networks:
    dev-network:
        driver: bridge

volumes:
    dbdata: